spring:
  application:
    name: personal-project
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/schedule
    username: root
    password: 1319
  security:
    jwt:
      header: Authorization
      secret: c7Iqk7YyM66W07YOA7L2U65Sp7YG065+9U3ByaW5n6rCV7J2Y7Yqc7YSw7LWc7JuQ67mI7J6F64uI64ukLg==
      token-validity-in-seconds: 60 * 60

      logging.level:
        org.hibernate.SQL: debug
        org.hibernate.type: trace

      mvc:
        pathmatch:
          matching-strategy: ant_path_matcher

